### ISSUE TITLE
Ask for a little help!

### ISSUE THREAD

**Issue by rlaace423** [mighildotcom/X230-Hackintosh#1]
First of all, thank you for your beautiful works for x230! 

I've used x230 as mohave, and worked great. 
Today, I upgraded x230 to catalina by native apple way (system preferences).

After that, my audio device is not detectable anymore. So I'm trying to ask for your help.

My question is that 
All I have to do is just replace /Volumes/EFI/EFI folders with your EFI folder? 
Is there anything I have to concern? 

(Plus) I've changed my wifi card with another one, and someone hacked my bios so works well.
So I think some kexts about wifi will not be needed.
All the other parts are vanilla ( with intel i5 ).

Thank you :)

**Comment by mighildotcom** [comment]
You have two options:

1. “Your audio device is not detectable”. Go ahead and update the kexts. It would work. Let me assume you’re using AppleALC. It’s got an update for Catalina. Just update it or use VooDooHDA instead. I recommend this first.. instead of replacing your EFI with mine.

2.  Back up your EFI folder and replace with mine. It will work! No need to worry about anything else. Is your X230 an i7 model?

And yeah, remove my WiFi kexts within the EFI folder. You wouldn’t need that.

~M

On Oct 23, 2019, at 1:02 AM, Sam (Sangho Kim) <notifications@github.com> wrote:

﻿

First of all, thank you for your beautiful works for x230!

I've used x230 as mohave, and worked great.
Today, I upgraded x230 to catalina by native apple way (system preferences).

After that, my audio device is not detectable anymore. So I'm trying to ask for your help.

My question is that
All I have to do is just replace /Volumes/EFI/EFI folders with your EFI folder?
Is there anything I have to concern?

(Plus) I've changed my wifi card with another one, and someone hacked my bios so works well.
So I think some kexts about wifi will not be needed.

Thank you :)

**Comment by verfasor** [comment]
You have two options:

1. “Your audio device is not detectable”. Go ahead and update the kexts. It would work. Let me assume you’re using AppleALC. It’s got an update for Catalina. Just update it or use VooDooHDA instead. I recommend this first. instead of replacing your EFI with mine.

2.  Back up your EFI folder and replace it with mine. It will work! No need to worry about anything else. 

And yeah, remove my WiFi kexts within the EFI folder. You wouldn’t need that.

~M

Edit: sorry, didn't notice you've already mentioned the CPU variant.

**Comment by rlaace423** [comment]
Finally I successfully made audio working!

Because of my kexts are messed around.. I simply reinstalled catalina and used your repo.
It work like a charm :) 

Thank you for your help!
